//
// quat_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_QUAT_ISPC_H
#define ISPC_QUAT_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
///////////////////////////////////////////////////////////////////////////
// Vector types with external visibility from ispc code
///////////////////////////////////////////////////////////////////////////

#ifndef __ISPC_VECTOR_float3__
#define __ISPC_VECTOR_float3__
#ifdef _MSC_VER
__declspec( align(16) ) struct float3 { float v[3]; };
#else
struct float3 { float v[3]; } __attribute__ ((aligned(16)));
#endif
#endif

#ifndef __ISPC_VECTOR_int32_t2__
#define __ISPC_VECTOR_int32_t2__
#ifdef _MSC_VER
__declspec( align(16) ) struct int32_t2 { int32_t v[2]; };
#else
struct int32_t2 { int32_t v[2]; } __attribute__ ((aligned(16)));
#endif
#endif

#ifndef __ISPC_VECTOR_float4__
#define __ISPC_VECTOR_float4__
#ifdef _MSC_VER
__declspec( align(16) ) struct float4 { float v[4]; };
#else
struct float4 { float v[4]; } __attribute__ ((aligned(16)));
#endif
#endif



#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void quat_ispc_v1_cos(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_pow_1(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_pow_2(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_pow_3(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_pow_4(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_pow_5(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_pow_6(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v1_sin(float3   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float mod_q, float max_len_sqr);
    extern void quat_ispc_v2_cos(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_pow_1(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_pow_2(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_pow_3(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_pow_4(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_pow_5(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_pow_6(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
    extern void quat_ispc_v2_sin(float4   * points, int32_t2   * indices, float4   * c, int32_t point_buf_count, uint8_t iter_min, uint8_t iter_max, float max_len_sqr);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_QUAT_ISPC_H
